#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
# Requirements:
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands to automatically
#+ configure a Ubuntu machine to respect above requirements
# Using what you did with 1-install_nginx_web_server, write 3-redirection so
#+ that it configures a brand new Ubuntu machine to the requirements
#+ asked in this task
#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using
#+ curl, it must return a page that contains the string Hello World
sudo apt-get -y update &&\
        sudo apt-get -y install nginx &&\
        sudo service nginx start &&\
        echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html &&\
        echo "Ceci n'est pas une page." | sudo tee /usr/share/nginx/html/custom_404.html &&\
        sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default &&\
        sudo service nginx restart &&\
        sudo service nginx reload
