#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
sudo sed -i "s/http {/http {\n\n\tadd_header X-Served-By $hostname;\n/" /etc/nginx/nginx.conf && sudo service nginx reload
