#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i "s/\tlisten 8080 default_server;/\tlisten 80 default_server;/" /etc/nginx/site-enable/default
sudo sed -i "s/\tlisten [::]:8080 default_server ipv6only=on;/\tlisten [::]:80 default_server ipv6only=on;/" /etc/nginx/site-enable/default
sudo service nginx restart
