#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/site-enable/default
sudo service nginx restart
kill -9 "$(cat /run/nginx.pid)"
