#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.
#script only displays:
#username
#user id
#Home directory path for the user
#Requirements:
#You must use the while loop (for and until are forbidden)
while IFS= read -r line;
do
	echo "$line" | cut -d: -f 1,3,6 
done < /etc/passwd
