#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
#must use the while loop
h=0
m=1
while [ $h -le 12 ]
do
	echo "Hour : $h"
	m=1
	while [ $m -lt 60 ]
	do
		echo $m
		(( m++ ))
	done
	(( h++ ))
done
