#!/usr/bin/env bash
#Bash script that displays: The content of the current directory In a list format
#Where only the part of the name after the first dash is displayed
#must use the for loop. Do not display hidden files
list=$(ls)
for file in $list
do
	 echo "$file" | cut -f 2 -d '-'
done
