#!/usr/bin/env bash
# Resolves localhost to 127.0.0.2
# Resolves facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i 8.8.8.8\t\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
