#!/usr/bin/env bash
# comfigure nginx to run as annother user passed as an argument
sudo -E -u nginx  "$(service nginx start)"
sudo -E -u nginx sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx reload

